language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
cache:
  directories:
    - "$HOME/.npm"
matrix:
  fast_finish: true
  include:
    - env: api
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/api
        - npm install
      script:
        - npm test
        # - npm run build
    - env: web
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/web
        - npm install
      script:
        - npm test
        # - npm run build
# on:
  # branch: master