language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "$HOME/.npm"
matrix:
  fast_finish: true
  include:
    - env: api
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/api
        - npm install
      script:
        - npm test
        - npm run build
    - env: web
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/web
        - npm install
      script:
        - npm test
        - npm run build
# on:
  # branch: master